# -*- coding: utf-8 -*-
"""pro-130.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dQcsYp-YMzAVP7dkcz1dDKUEMJvShXLZ
"""

import pandas as pd
import csv

df = pd.read_csv("/content/total_stars.csv")
print(df.columns)

df.drop(['Unnamed: 0','Unnamed: 6', 'Star_name.1', 'Distance.1', 'Mass.1', 'Radius.1'],axis=1,inplace=True)

df.drop("Luminosity",axis=1,inplace=True)

print(df)

cleaned_df = df.dropna()
print(cleaned_df)

cleaned_df.to_csv('cleaned_data.csv')